# -*- coding: utf-8 -*-
"""fundamantal00.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pkB3guVnWnREfS3g2Z9Evvw-xfwMXh0
"""

# scalar
import torch
scalar = torch.tensor(7)
scalar
scalar.item()

# vector
vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])

MATRIX

MATRIX[0]

# tensor
TENSOR = torch.tensor([[[1,2,3],[3,5,6],[3,4,6]]])

TENSOR

TENSOR.shape

### Random tensors

random_tensor = torch.rand(1,3,4)

random_tensor

# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#hight,width,colour channels(R,G,B)
random_image_size_tensor.shape

"""# Creating the range in the pytorch"""

torch.arange(1,100,3)

"""# Tensor datatypes"""

float_32_tensor = torch.tensor([3.0,6.0,9.0])
float_32_tensor

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

int_16_tensors = torch.tensor([3,4,5],dtype=torch.int16)
int_16_tensors.add(20)*float_32_tensor

"""Matrix multiplication"""

tensor = torch.tensor([2,4,5])
value = 0
for i in range (len(tensor)):
  value += tensor[i]*tensor[i]
print (value)

torch.matmul(tensor,tensor)

"""the the shape error and how to solve them

"""

torch.matmul(torch.rand(2,3),torch.rand(3,3)).shape

tensor_a = torch.tensor([[[2,3,4],[3,4,5],[6,4,67]]])
tensor_b = torch.tensor([[[4,3,5],[2,6,7],[2,6,8]]])
torch.matmul(tensor_b.mT,tensor_a)

